server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: zhengweicheng
    driver-class-name: com.mysql.jdbc.Driver
  application:
    #nameï¼šorderservice
    name: orderservice
mybatis:
  type-aliases-package: com.xn2001.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.xn2001: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka